# process topography params
sigma = 1.5

# reach segmentation params
hand_threshold = 10
spacing = 20
minsize = 100
window = 3

# xsection params:
line_spacing = 10
line_width = 1000
point_spacing = 10

# profile preprocessing params
min_hand_jump = 15
ratio = 2.5
min_distance = 50
min_peak_prominence = 10

# max ascent params
num_cells = 3

# slope thresholds 
plains_threshold = 4
hillslope_threshold = 20
slope_threshold = 10

# floor threhsolds
buffer = 1
min_points = 15
percentile = 0.75
