# process topography params
sigma = 1.5

# reach segmentation params
num_points = 200
spacing = 20

# xsection params:
line_spacing = 3
line_width = 100
point_spacing = 1

# profile preprocessing params
min_hand_jump = 15
ratio = 2.5
min_distance = 10

# profile curvature params
distance = 1
height = 0.0

# max ascent params
num_cells = 5

# slope thresholds 
plains_threshold = 4
hillslope_threshold = 20
slope_threshold = 10

# floor threhsolds
buffer = 1
min_points = 15
quantile = 0.80
