# process topography params
sigma = 1.5

# reach segmentation params
num_points = 200
spacing = 20
minsize = 200
window = 4

# xsection params:
line_spacing = 10
line_width = 1000
point_spacing = 10

# profile preprocessing params
min_hand_jump = 15
ratio = 2.5
min_distance = 50

# profile curvature params
distance = 1
height = 0.0

# max ascent params
num_cells = 3

# slope thresholds 
plains_threshold = 4
hillslope_threshold = 20
slope_threshold = 10

# floor threhsolds
buffer = 1
min_points = 15
quantile = 0.80
